### ISSUE TITLE
About me game-navigation?

### ISSUE THREAD

**Issue by simonszc** [mevans72/portfolio#20]
The about me game changes your navigation bar on it in a way that seems inappropriate for a single-page app. either remove the nav bar and provide just a "back" functionality, or keep the nav bar the same. Just having a "home" tab is odd.

**Comment by mevans72** [comment]
Thanks for the recommendation. I opted for the "back" functionality in this instance (i.e., swapping home for back), as I preferred to go with a minimal approach to the nav bar when transitioning from 'the site' to 'the game'.
