### ISSUE TITLE
Overdoing it on classes and ids?

### ISSUE THREAD

**Issue by simonszc** [mevans72/portfolio#22]
There are a LOT of classes and ids on your html. Are you over selecting? Which ones do you NEED?

**Comment by mevans72** [comment]
Thanks for the recommendation. While I have been 'hacking' away at things and the code is indeed in need of some cleanup, I'll be removing all of the unneeded classes and ids as I continue to DRY out this code. I went ahead and did a first pass to clean some of these up, but more to come.
